name: Extract PR information from a workflow run event
description: >
  When a workflow_run workflow is triggered by a workflow that was, in turn,
  triggered by a pull request, sometimes you need the detailed information
  about the pull request. This action extracts the PR information from the
  workflow run event and sets it as output variables.


inputs:
  github-token:
    description: 'The GitHub token to use for API requests.'
    required: true

outputs:
  pr-number:
    description: The number of the pull request.
    value: ${{ steps.prnum.outputs.pr-number }}
  pr-headsha:
    description: The head SHA of the pull request.
    value: ${{ steps.headsha.outputs.pr-headsha }}
  #pr-title:
    #description: The title of the pull request.
    #value: ${{ steps.extract.outputs.pr-title }}
  #pr-body:
    #description: The body of the pull request.
    #value: ${{ steps.extract.outputs.pr-body }}
  #pr-author:
    #description: The author of the pull request.
    #value: ${{ steps.extract.outputs.pr-author }}

runs:
  using: 'composite'
  steps:
    - name: Extract HEAD SHA
      id: headsha
      shell: bash
      run: |
        HEAD_SHA=$(jq -r '.workflow_run.head_commit.id' "$GITHUB_EVENT_PATH")
        echo "pr-headsha=$HEAD_SHA" | tee -a "$GITHUB_OUTPUT"

    - name: Get PRs
      uses: octokit/graphql-action@v2.x
      id: prs
      with:
        query: |
          query {
            repository(owner: "${{ github.repository_owner }}", name: "${{ github.event.repository.name }}") {
              pullRequests(first: 100, states: [OPEN], orderBy: { field: UPDATED_AT, direction: DESC }) {
                nodes {
                  number
                  headRefOid
                }
              }
            }
          }
      env:
        GITHUB_TOKEN: ${{ inputs.github-token }}

    - name: Extract PR data for HEAD SHA
      shell: bash
      id: prnum
      run: |

        echo "${{ steps.prs.outputs.data }}"

        MATCHING_PRS=$(echo ${{ steps.prs.outputs.data }} | jq --arg sha "$HEAD_SHA" '.data.repository.pullRequests.nodes | map(select(.headRefOid == $sha))')
        echo $MATCHING_PRS
        COUNT=$(echo "$MATCHING_PRS" | jq 'length')

        if [ "$COUNT" -eq 0 ]; then
          echo "No pull request found associated with HEAD_SHA: ${HEAD_SHA}" >&2
          exit 1
        elif [ "$COUNT" -eq 1 ]; then
          PR_NUMBER=$(echo "$MATCHING_PRS" | jq -r '.[0].number')
          echo "pr-number=$PR_NUMBER" | tee -a "$GITHUB_OUTPUT"
        else
          echo "Error: Multiple pull requests found with HEAD_SHA ${HEAD_SHA}. Unable to determine the correct PR." >&2
          exit 1
        fi
