name: 'test-deployment-count'
description: 'Ensure a specific number of Cloudflare Pages deployments on a branch'
inputs:
  CLOUDFLARE_API_TOKEN:
    description: 'Cloudflare API token (from secrets)'
    required: true
  CLOUDFLARE_ACCOUNT_ID:
    description: 'Cloudflare account ID (from secrets)'
    required: true
  CLOUDFLARE_PROJECT_NAME:
    description: 'Cloudflare Pages project name (from repo variables)'
    required: true
  branch_name:
    description: 'Branch to inspect'
    required: true
  n_deployments:
    description: 'Expected number of deployments'
    required: true
runs:
  using: 'composite'
  steps:
    - name: Fetch deployments for branch
      id: fetch_deployments
      shell: bash
      run: |
        set -euo pipefail
        response=$(curl -s \
          -H "Authorization: Bearer ${{ inputs.CLOUDFLARE_API_TOKEN }}" \
          "https://api.cloudflare.com/client/v4/accounts/${{ inputs.CLOUDFLARE_ACCOUNT_ID }}/pages/projects/${{ inputs.CLOUDFLARE_PROJECT_NAME }}/deployments?branch=${{ inputs.branch_name }}&per_page=100")
        count=$(echo "$response" | jq '.result | length')
        echo "count=$count" | tee -a "$GITHUB_OUTPUT"

    - name: Validate deployment count
      shell: bash
      run: |
        if [ "${{ steps.fetch_deployments.outputs.count }}" -ne ${{ inputs.n_deployments }} ]; then
          echo "::error::Expected ${{ inputs.n_deployments }} deployments on branch '${{ inputs.branch_name }}', but found ${{ steps.fetch_deployments.outputs.count }}."
          exit 1
        fi
