name: 'test-deployment-count'
description: 'Ensure a specific number of Cloudflare Pages deployments on a branch'
inputs:
  CLOUDFLARE_API_TOKEN:
    description: 'Cloudflare API token (from secrets)'
    required: true
  CLOUDFLARE_ACCOUNT_ID:
    description: 'Cloudflare account ID (from secrets)'
    required: true
  CLOUDFLARE_PROJECT_NAME:
    description: 'Cloudflare Pages project name (from repo variables)'
    required: true
  branch_name:
    description: 'Branch to inspect'
    required: true
  n_deployments:
    description: 'Expected number of deployments'
    required: true
runs:
  using: 'composite'
  steps:
    - name: Fetch deployments for branch
      id: fetch_deployments
      uses: 'omsf/static-site-tools/get-cloudflare-pages-deployments@main'
      with:
        CLOUDFLARE_API_TOKEN: ${{ inputs.CLOUDFLARE_API_TOKEN }}
        CLOUDFLARE_ACCOUNT_ID: ${{ inputs.CLOUDFLARE_ACCOUNT_ID }}
        CLOUDFLARE_PROJECT_NAME: ${{ inputs.CLOUDFLARE_PROJECT_NAME }}
        branch_name: ${{ inputs.branch_name }}

    - name: Validate deployment count
      shell: bash
      run: |
        count=$(echo '${{ steps.fetch_deployments.outputs.deployments }}' | jq '. | length')
        if [ $count -ne ${{ inputs.n_deployments }} ]; then
          echo "::error::Expected ${{ inputs.n_deployments }} deployments on branch '${{ inputs.branch_name }}', but found ${{ steps.fetch_deployments.outputs.count }}."
          exit 1
        fi
