name: Run website tests
description: Run common tests on a built website

inputs:
  site-directory:
    description: The directory containing the built website
    required: true
  base-url:
    description: The base URL of the website
    required: true


runs:
  using: 'composite'
  steps:
    - name: Define lychee args
      shell: bash
      run: |
        if [ "${{ inputs.base-url }}" ]; then
          LYCHEE_ARGS="--base ${{ inputs.base-url }} "
        fi
        LYCHEE_ARGS="${LYCHEE_ARGS}${{ inputs.site-directory }}/"
        echo "LYCHEE_ARGS=$LYCHEE_ARGS" >> $GITHUB_ENV
          
    - name: Check links
      uses: lycheeverse/lychee-action@v2
      with:
        args: ${{ env.LYCHEE_ARGS }}
