name: Build from PR

on: 
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          submodules: 'recursive'

      - name: Build site
        #uses: omsf/static-site-tools/build/hugo@main
        uses: ./build/hugo  # dev
        with:
          base-url: ""
          source-directory: ${{ vars.HUGO_SOURCE_DIR }}
          output-directory: ${{ vars.HUGO_OUTPUT_DIR }}


      - name: Test site
        uses: omsf/static-site-tools/common-tests@main
        with:
          site-directory: ${{ vars.HUGO_SOURCE_DIR }}/${{ vars.HUGO_OUTPUT_DIR}}
          base-url: ""

      - name: Make artifact
        shell: bash
        run: tar czf site.tar.gz ${{ vars.HUGO_SOURCE_DIR }}/${{ vars.HUGO_OUTPUT_DIR }}

      - name: Upload artifact
        if: ${{ github.event_name != 'schedule' }}
        uses: actions/upload-artifact@v4
        with:
          name: site-build
          path: site.tar.gz
          if-no-files-found: error
          retention-days: 1
