name: Deploy to production

on:
  workflow_run:
    workflows: ["Build from push"]
    types:
      - completed
    branches:
      - main

jobs:
  deploy-to-prod:
    if: ${{ (github.event.workflow_run.conclusion == 'success') && (github.repository == vars.MAIN_REPO) }}
    uses: omsf/static-site-tools/.github/workflows/prod-cloudflare.yaml@main
    with:
      run-id: ${{ github.event.workflow_run.id }}
      project-name: ${{ vars.CLOUDFLARE_PROJECT_NAME }}
      html-dir: ${{ vars.HUGO_OUTPUT_DIR || 'public' }}
    secrets:
      CLOUDFLARE_API_TOKEN: ${{ secrets.CLOUDFLARE_API_TOKEN }}
      CLOUDFLARE_ACCOUNT_ID: ${{ secrets.CLOUDFLARE_ACCOUNT_ID }}
