name: Deploy to production

on:
  workflow_call:
    inputs:
      run-id:
        description: "The ID of the workflow run that produced the artifact"
        required: true
        type: number
      project-name:
        description: "Name of the project in Cloudflare Pages"
        required: true
        type: string
      html-dir:
        description: "Root directory name for the site HTML artifact (usually 'public' for Hugo, '_site' for Jekyll, etc.)"
        required: true
        type: string
      remote-subdir:
        description: "Subdirectory of the site to deploy to"
        required: false
        type: string
        default: ""
    secrets:
      CLOUDFLARE_API_TOKEN:
        description: "API token for Cloudflare"
        required: true
      CLOUDFLARE_ACCOUNT_ID:
        description: "Account ID for Cloudflare"
        required: true

jobs:
  deploy-from-artifact:
    runs-on: ubuntu-latest
    steps:
      - name: Download artifact
        uses: actions/download-artifact@v4
        with:
          run-id: ${{ inputs.run-id }}
          name: "site-build"
          github-token: ${{ secrets.GITHUB_TOKEN }}

        # TODO: split this off into an internal action?
      - name: Unpack artifact
        run: |
          tar -xzf site.tar.gz
          rm site.tar.gz

          mkdir deploy-dir
          if [ -n "${{ inputs.remote-subdir }}" ]; then
            mkdir -p deploy-dir/${{ inputs.remote-subdir }}
            mv ${{ inputs.html-dir }}/* deploy-dir/${{ inputs.remote-subdir }}
          else
            mv ${{ inputs.html-dir }}/* deploy-dir
          fi

      - name: Upload to Cloudflare Pages
        uses: cloudflare/wrangler-action@v3
        with:
          apiToken: ${{ secrets.CLOUDFLARE_API_TOKEN }}
          accountId: ${{ secrets.CLOUDFLARE_ACCOUNT_ID }}
          command: pages deploy deploy-dir --project-name ${{ inputs.project-name }} --branch main
